### PR TITLE
refactoring and enhancement

### PR DESCRIPTION
**Pull request by gilcot**
(see commit messages)

### CODE REVIEW

**Comment by iamgini** [comment]
@gilcot sorry, not sure so many changes and you pull back to my master repo :)
Is that by mistake or purposefully raised a PR with suggestions ? 

Thanks.

**Comment by gilcot** [comment]
Hello @ginigangadharan 

No mistake, I forked in order to work on some scripts then reflow back with this PR. :) 

Regards

**Comment by iamgini** [comment]
@gilcot 
Thats great, thanks for that.

**Comment by iamgini** [comment]
@gilcot I have merged the same... 
(y)

**Comment by gilcot** [comment]
Glad you had time to review the code and test the changes (I've tried to not break how they work, but I wasn't sure my own tests catched all cases.) 
Thanks to you.

**Comment by iamgini** [comment]
@gilcot sure, I will do some checks later.
rarely using those scripts nowadays (as I changed my job and role)

Thanks for suggestions :)

**Pull request merged**
